version: '3.4'

networks:
  overlay:

volumes:
  pg_data:
    driver: local
  pg_admin:
    driver: local

services:
  database:
    image: postgres:16.1
    container_name: postgres
    ports:
      - 5432:5432
    enviroment:
      POSTGRES_PASSWORD: postgres
    networks:
      overlay
    volume:
      - pg_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 80:80
    enviroment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - overlay
    volumes:
      - pg_admin:/var/lib/pgadmin
      